% Maps a simple_auth object with the following properties
%   => Id (Can be generated by Chicago BossDB
%   => Username (Our authentication username)
%   => Password (Our authentication password)

% Now to create a new object we can simply call the following statement:
% SimpleAuth = simple_auth:new(id,"superusername","superpassword").

-module(simple_auth, [Id, Username, Password]).
-compile(export_all).